language: php
php:
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev

script:
  - phpunit --coverage-clover clover.coverage

after_script:
  - php vendor/bin/codacycoverage clover clover.coverage
